### ISSUE TITLE
Considering deprecate the sample "Beam"

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#105]
https://github.com/Dedac/Beam

Last update 9 months ago.

**Comment by AdrienTorris** [comment]
@Dedac Is there any plan to update this sample?

**Comment by Dedac** [comment]
@AdrienTorris I am actually planning on updating it in the next week or so.

**Comment by Dedac** [comment]
I have updated the sample, I think that we can close this issue

**Comment by AdrienTorris** [comment]
Hi @Dedac.

Perfect, thank you very much.
