### ISSUE TITLE
Considering deprecate the sample "BlazeDown"

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#107]
https://github.com/EdCharbeneau/BlazeDown

Last update 10 months ago.

**Comment by AdrienTorris** [comment]
@EdCharbeneau Is there any plan to update this sample?

**Comment by EdCharbeneau** [comment]
Yes, I was waiting for the churn to settle. I will give it an update when the next preview ships.

Thanks for the reminder.

**Comment by AdrienTorris** [comment]
Ok, so I don't move this sample and close this issue. Thank you for your answer.

**Comment by EdCharbeneau** [comment]
BlazeDown has been updated to reflect changes in ASP.NET Core Preview 6. @AdrienTorris Thank you for keeping on top of this.
