### ISSUE TITLE
Considering deprecate the sample "vocadb"

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#111]
https://github.com/riipah/vocadb-lyrics-blazor-proto

Last update last year.

**Comment by AdrienTorris** [comment]
@riipah Is there any plan to update this sample?

**Comment by riipah** [comment]
I'm quite busy right now. I will probably update it at some point when Blazor stabilizes. It doesn't really make sense to keep updating to latest preview every month or so. Since this was written for a very early version of Blazor and it's not too complicated, I will probably just rewrite it.

**Comment by AdrienTorris** [comment]
Ok. Thank you for your response. I will move it to the "Deprecated" section, feel free to re-move it when it will be updated.
