### ISSUE TITLE
Considering deprecate the sample "Blazor.DataDrivenLayout"

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#120]
https://github.com/hutchcodes/Blazor.DataDrivenLayout

Last update 9 months ago.

**Comment by AdrienTorris** [comment]
@hutchcodes Is there any plan to update this sample?

**Comment by hutchcodes** [comment]
This definitely needs to be updated, but I won't have time for a while (maybe in July?). Maybe the thing to do is to remove it and I'll just submit it again when I do get it updated.

**Comment by AdrienTorris** [comment]
Ok, thank's for the feedback. I moved this item to the 'obsolete' section. Feel free to move it back if make an update.
