### ISSUE TITLE
Considering deprecate the sample "blazorpong"

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#121]
https://github.com/ctrl-alt-d/blazorpong

Last update 11 months ago.

**Comment by AdrienTorris** [comment]
@ctrl-alt-d Is there any plan to update this sample?

**Comment by ctrl-alt-d** [comment]
Nope, please, remove it from the list. Maybe, some day, we rewrite it from scratch. Thanks. Good work!

**Comment by AdrienTorris** [comment]
Ok, thank's for replying.
