### ISSUE TITLE
WASM: The assembly mscorlib.dll was not found or could not be loaded. blazor.webassembly.js:1 WASM: It should have been installed in the `/mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/sdks/out/wasm-runtime-release/lib/mono/4.5/mscorlib.dll' directory

### ISSUE THREAD

**Issue by VerCaparas1024** [AdrienTorris/awesome-blazor#135]
![image](https://user-images.githubusercontent.com/52057569/59892144-8c8ac800-940a-11e9-9736-a27a0caadd9e.png)

Hi I got this problem when debugging my app, I reinstall it and follow the proper steps from docs but still i got this error.

Can someone please tell me the solution to this

**Comment by AdrienTorris** [comment]
Hi. I think StackOverflow will be a better help.

**Comment by AdrienTorris** [comment]
https://stackoverflow.com/
