### ISSUE TITLE
Make GitHub releases  when adding items.

### ISSUE THREAD

**Issue by BenjaBobs** [AdrienTorris/awesome-blazor#146]
If you make releases when you add stuff (i.e. not typos and such) we can Watch releases and be notified. 😃

**Comment by AdrienTorris** [comment]
Hi. 
It's a good idea, thanks.
I don't think it's a good idea to create a new release each time I add some content but I have to think about it, it's definitely a good idea to use releases. I'll think about that, thanks!

**Comment by atifaziz** [comment]
> I don't think it's a good idea to create a new release each time

How about a monthly release (August 2019, September 2019, etc.) with a diff of changes to `README.md`? The diff is easy to do with `git diff aug19..sep19 README.md` if tagged so.

**Comment by stsrki** [comment]
I agree with @atifaziz that monthly release would be the best.

**Comment by AdrienTorris** [comment]
Yes it's a good idea.

**Comment by ctrl-alt-d** [comment]
Making community :+1:

**Comment by AdrienTorris** [comment]
First release very soon 🎉

**Comment by AdrienTorris** [comment]
I think to use the tags like this: _2019.07_ (for July), then _2019.08_, ...

Is it sound like a good idea?

**Comment by atifaziz** [comment]
> Is it sound like a good idea?

Yes & thanks for working towards it! We need to bot-ize this next so you can go to the beach and stay there! 😄 It would also benefit other awesome lists and their readers!

**Comment by AdrienTorris** [comment]
And the first release is here! https://github.com/AdrienTorris/awesome-blazor/releases/tag/v2019.07

Thank's for this awesome idea!

**Comment by AdrienTorris** [comment]
Release of August : https://github.com/AdrienTorris/awesome-blazor/releases/tag/v2019.08
