### ISSUE TITLE
Consider using GitHub Badges to display stars

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#159]
https://github.com/ddavison/github-badges

Related to #157

**Comment by AdrienTorris** [comment]
Test: http://githubbadges.com/star.svg?user=adrientorris&repo=awesome-blazor&style=flat

**Comment by AdrienTorris** [comment]
Test: http://githubbadges.com/star.svg?user=chrissainty&repo=worddaze&style=flat

**Comment by stavroskasidis** [comment]
+ 1

**Comment by AdrienTorris** [comment]
test : http://githubbadges.com/star.svg?user=thangchung&repo=blog-core&style=flat

**Comment by AdrienTorris** [comment]
it's awesome! thank's @stavroskasidis !

**Comment by AdrienTorris** [comment]
`[![](http://githubbadges.com/star.svg?user=&repo&style=flat)]()`

**Comment by AdrienTorris** [comment]
But it doesn't seem very stable. At least half of the requests are 404s.

**Comment by stavroskasidis** [comment]
Hmm, maybe try some other service then ? How about this one ?
https://github.com/Naereen/badges

**Comment by stavroskasidis** [comment]
Here is a test for https://github.com/stavroskasidis/BlazorContextMenu
![GitHub stars](https://img.shields.io/github/stars/stavroskasidis/BlazorContextMenu.svg?style=social&label=Star)

**Comment by chrissainty** [comment]
I think https://shields.io/ is a good options as well. I use it for the badges on all my repos and it hasn’t let me down so far.

![GitHub stars](https://img.shields.io/github/stars/AdrienTorris/awesome-blazor)

**Comment by AdrienTorris** [comment]
shields.io looks perfect :)

**Comment by AdrienTorris** [comment]
I think we're done here, what do you think?

Thank's you all for your ideas and suggestions!

**Comment by AdrienTorris** [comment]
I think we can close this issue now, thank you all for your suggestions and energy! This repo is way better now than before 👍 

Don't hesitate to repoen this issue if you need.
