### ISSUE TITLE
ChartJs.Blazor is not maintained anymore

### ISSUE THREAD

**Issue by SeppPenner** [AdrienTorris/awesome-blazor#165]
ChartJs.Blazor should be marked as (not maintained) or something because it isn't maintained anymore...

![image](https://user-images.githubusercontent.com/9639361/62757080-549f1900-ba7a-11e9-919a-b89934721685.png)

As an alternative, I would already recommend @Joelius300's [ChartJSBlazor](https://github.com/Joelius300/ChartJSBlazor) where we try to fix all the issues from the original project. I will create a pull request for the changes as well.

**Comment by SeppPenner** [comment]
I have created a pull request for this here: https://github.com/AdrienTorris/awesome-blazor/pull/166

**Comment by AdrienTorris** [comment]
Thank you @SeppPenner
