### ISSUE TITLE
position: sticky started working on last version but now isn't & Canvas request

### ISSUE THREAD

**Issue by dbowser** [AdrienTorris/awesome-blazor#176]
We have been trying out Blazor and are very happy with our experience overall. 
I don't know if this is the best place to give feedback on this kind of thing but it is important to our project and it briefly kind of worked and now it seems that it does not at all with Version 16.3.0 Preview 2.0.

We are simply adding to our custom style sheet
th {
   position: sticky;
...
We expect the header to stay at the top as we scroll through a long table. 
That worked in the last version but doesn't now that we upgraded. 
Hopefully this and whatever is behind the change will be addressed.
We also remain hopeful that support for interacting with the Canvas will be provided with working examples. We found 3rd party support but it was quite dated and we had trouble getting it to work with the latest Blazor.

**Comment by AdrienTorris** [comment]
Hi,

Thank you for the message but we are just a community who maintain a list of interesting resources about Blazor, we are not official.

For a feedback, you can send a generic or a specific one on the Blazor's official website : https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor
You have a "Feedback" button on the right bottom of the screen, don't hesitate to send them a feedback it's valuable for Microsoft and Blazor.

Also if you have questions you can check StackOverflow (https://stackoverflow.com/questions/tagged/blazor) or the channel on Gitter about Blazor (https://gitter.im/aspnet/Blazor). The community is very active, I'm sure you will find there the help you need.

Have a good day :)
