### ISSUE TITLE
Video on how to Deploy a Blazor Server Side template on a Linux VPS

### ISSUE THREAD

**Issue by lKinderBueno** [AdrienTorris/awesome-blazor#180]
Hi,
I made a video tutorial on how to deploy a blazor server side app on a Ubuntu VPS Server, how to set Apache with all the mod to enable and the relative working configs.
I really wasted a week finding all the required settings, so I decided to make a video to help the others.
I know it's not the best of the videos, but still better than nothing.
If you want add it to the repository 
https://www.youtube.com/watch?v=69pj-2GJDCY

**Comment by AdrienTorris** [comment]
Just saw this issue, very sorry. Video added to the archive.
https://github.com/AdrienTorris/awesome-blazor/releases/tag/v2020.W32
https://github.com/AdrienTorris/awesome-blazor/blob/master/Archives/2019.md
