### ISSUE TITLE
Last Commit date to show active projects

### ISSUE THREAD

**Issue by enkodellc** [AdrienTorris/awesome-blazor#187]
I would like to suggest putting a last commit badge on projects to help viewers see which projects are still active: 

https://shields.io/category/activity
GitHub last commit: |   | /github/last-commit/:user/:repo

**Comment by AdrienTorris** [comment]
Hi

It such a great idea. I'll definitely check that in the next few days...

**Comment by AdrienTorris** [comment]
I'd just made some tests and I find your idea very excellent! Thank's you for this, I'll update the others samples et components this next few days.
Thank's you for your awesome contribution.

**Comment by enkodellc** [comment]
You're welcome @AdrienTorris . Thanks for keeping the list maintained, it should definitely help visitors to find inactive repos. I know had to go to each repo when I was looking through the repos listed. I have been getting a few people to my repo through this page.  https://github.com/enkodellc/blazorboilerplate.
