### ISSUE TITLE
Just added a new blazor project to my github

### ISSUE THREAD

**Issue by shawty** [AdrienTorris/awesome-blazor#200]
Hi Adrien,

I just added the following project:

https://github.com/shawty/simpleloggingserver

to my github repo.

It's a simple logging server written using blazor.  Nothing special or big/clever, just a simple server that accepts log requests posted to it and displays them, I use it for remote display of "console.log" messages on remote JS code while debugging things.

Feel free to add it to your utilities section if you wish, and if not just kill this issue :-)

shawty

**Comment by michalkrzych** [comment]
It looks like writing up the readme.md actually took longer than writing the app itself ;) If I may suggest a small "security" improvement to consider in the future: at least add some basic authentication or with just a bit more effort use gRPC proto contracts along with some basic server-side model validation.

**Comment by shawty** [comment]
@michalkrzych LOL... not quite, it took me a weekend to get bloody signalr working correctly :-) 

The MOST annoying part however, was searching for a suitable system to use, not finding any, then spending 2 days writing that, and 30 minutes after uploading it to GH finding "jsconcole.com" and "VorlonJS" both of which put my simple little logger to shame :-)

Future improvements, maybe, we'll see, it does what I need it to do, feel free to fork it yourself and have a play :-)

**Comment by AdrienTorris** [comment]
Hi

Very sorry for the delay, I added it.

**Comment by AdrienTorris** [comment]
Thank you for submitting this!

**Comment by shawty** [comment]
No worries Adrian :-)
