### ISSUE TITLE
Add a 'Newly Added/Updated' Section

### ISSUE THREAD

**Issue by 274188A** [AdrienTorris/awesome-blazor#211]
The task of keeping abreast of what's been added or updated is a bit cumbersome (for example checking the commits).

I think it would be a nice idea to having a daily (get wiped clean daily) summary/list of new updated links.

**Comment by AdrienTorris** [comment]
Hi

It's an interesting idea. 

Do you prefer a weekly section (a daily one will be to hard to maintain) in the readme or a file per week in a dedicated folder ? (like a folder named 'Releases' which can contain a file per week).

**Comment by 274188A** [comment]
weekly is fine by me and i understand this is a bit arduous long term...
but i think looking ahead this resource could get really large and unwieldy if not for some kind of summary of changes.

**Comment by 274188A** [comment]
i wonder if github actions could assist? ie by extracting info and creating a comment - not sure myself just putting it out there...

**Comment by AdrienTorris** [comment]
Another solution is to create a detailed release a week instead of a release per month. It could be great.

**Comment by AdrienTorris** [comment]
I just activate notifications by mail, I think it will be not that hard to create weekly releases with the list of added items. I'll try for a few weeks! Keep in touch :)

**Comment by AdrienTorris** [comment]
I publish now a release a week with the detail of what was added: https://github.com/AdrienTorris/awesome-blazor/releases

I hope it will help.
