### ISSUE TITLE
Consider adding video from Steve Sanderson

### ISSUE THREAD

**Issue by mylabbook** [AdrienTorris/awesome-blazor#216]
Consider adding https://www.youtube.com/watch?v=6BT2AF9PO5g
a video by Steve Sanderson from NDC Sydney October 2019 covering an example and the past and future of Blazor

**Comment by AdrienTorris** [comment]
It seems the same video as this one: https://www.youtube.com/watch?v=6BT2AF9PO5g&feature=youtu.be
