### ISSUE TITLE
Newly added items should have a `NEW` mark.

### ISSUE THREAD

**Issue by dimohy** [AdrienTorris/awesome-blazor#242]
I visit here periodically. I'm fascinated with Blazor technology and have a desire to quickly find a new entry.
However, since there are so many contents, it is not immediately known which item was added.
If there is a newly added item, `NEW` appears in front of it, so accessibility is good.

What do you think?

**Comment by knight1219** [comment]
How long should something be marked as new, one-2 months? With how fast Blazor is evolving, maybe even only a few weeks?

This could get hard to try and maintain.

**Comment by imtrobin** [comment]
how about entering the date of addition instead

**Comment by dimohy** [comment]
If after some time GitHub cannot automatically remove the 'new' mark, I agree that the approach I proposed can be very difficult in terms of document changes.

In any case, the demand for the same or similar features does not change.

In another problem, there was a way to manage new items individually. It is also good. Anyway, I think it's not right to track the updated content as a GitHub commit change. (It's not a document, so it's hard to read from a document's point of view).

**Comment by knight1219** [comment]
What if we just simply separate things by year of addition, Something like 

- General
-- 2020
-- 2019
-- 2018
-- Older

This way it's just built into the lists automatically.

**Comment by AdrienTorris** [comment]
A solution could be to have detailed releases. One per month, or one per week. I have to organize myself to do this.

**Comment by AdrienTorris** [comment]
Related #211

**Comment by AdrienTorris** [comment]
I just activate notifications by mail, I think it will be not that hard to create weekly releases with the list of added items. I'll try for a few weeks! Keep in touch :)

**Comment by 274188A** [comment]
I'm starting to wonder if this page has out grown GitHub.  maybe a dedicated site that can provide better filtering and ordering capabilities for users would work better.

**Comment by stsrki** [comment]
@274188A It happened what I said a long time ago. If you accept anyone PR, eventually you will have too many things that don't have any benefits other that to be on the list. And now it's difficult to find the good one.

**Comment by AdrienTorris** [comment]
Hi.

I agree this page is becoming too massive to be usefull.

I'll work on a explorer web app to have an exhaustive and searchable list of what exists around Blazor, this will allow me to be a way more restrictive about the quality of the items listed here.

I'll work on it ASAP, we keep in touch.

**Comment by AdrienTorris** [comment]
For now you can watch the releases, I publish a release a week with the detail of the items there were added: https://github.com/AdrienTorris/awesome-blazor/releases

**Comment by AdrienTorris** [comment]
Can I close this issue? Are the releases match the need?

**Comment by stsrki** [comment]
I think latest releases are the right way to handle the new items.

**Comment by dimohy** [comment]
I think it matches. Thank you!
