### ISSUE TITLE
Sample Submission

### ISSUE THREAD

**Issue by MelbourneDeveloper** [AdrienTorris/awesome-blazor#244]
Hi,

I have put together a sample for hitting a RESTful API with RestClient.Net. I wrote an article about it [here](https://christianfindlay.com/2020/02/14/blazor-webassembly-rest-client/). It works with client and server-side rendering. The sample can be cloned [here](https://github.com/MelbourneDeveloper/RestClient.Net/tree/master/RestClient.Net.Samples.Blazor). It would be awesome if you could list it. 

Thanks
Christian Findlay

**Comment by MelbourneDeveloper** [comment]
@AdrienTorris Thanks so much for posting my article.

**Comment by AdrienTorris** [comment]
You are welcome @MelbourneDeveloper, your blog is great 👍
