### ISSUE TITLE
Testing Blazor Sites

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [AdrienTorris/awesome-blazor#247]
Is there any plan for how Blazor sites will be tested? I see Playwright https://github.com/microsoft/playwright as the closest thing so far. Not sure how well web assembly will work with sites going forward?

**Comment by chrissainty** [comment]
Steve Sanderson has released a prototype testing library [which you can find here](https://github.com/SteveSandersonMS/BlazorUnitTestingPrototype). There is also an [excellent testing library by Egil Hansen](https://github.com/egil/razor-components-testing-library) which builds on the features of Steves library but adds much more.

**Comment by SuperDaveOsbourne** [comment]
How will the screen scraping approach work if I want to test remotely? What are the implications if any?

**Comment by chrissainty** [comment]
Are you talking about testing a render of the UI? If so, any way you’ve done this with other frameworks should work wit Blazor

**Comment by AdrienTorris** [comment]
There is a great video from the last .NET Conf "Focus on Blazor" by Egil Hansen about testing Blazor components: https://channel9.msdn.com/Events/dotnetConf/Focus-on-Blazor/Testing-Blazor-Components
You probably should watch it.

**Comment by ray440** [comment]
You can try IcuBlazor: http://icublazor.com/index.html. Like Playwright, you can automate your UI, take snapshots and pixel-diff them.

**Comment by AdrienTorris** [comment]
Thank you all for the answers, I close this issue.
