### ISSUE TITLE
Blazor Circuit not Initialized

### ISSUE THREAD

**Issue by Beblia** [AdrienTorris/awesome-blazor#256]
Getting error where if user put there browser into sleep mode and comes back after 3 minutes my blazor app reconnects but the ui is not usable anymore. I have to do a manual refresh. Here is a screen shot of the chrome inspect log from an iPhone. Web socket reconnects after those 3 minutes but the circuit is not initialized. Shouldn't blazor create a new circuit and transfer the state from the old circuit? But in my website the circuit gets an error. This is very bad since users have to refresh the whole page after only putting away there browser for 3 minutes. Not a usable website. I spent 10 hours+ on this issue and no matter what I do on my server side (Windows Server 2019) or in my blalzor code nothing helps to change this outcome. Please help me out.
https://imgur.com/0NhqfsN

This is the last thing remaining from me finishing the site.

**Comment by chrissainty** [comment]
Hi @Beblia, 
May I suggest you raise your issue with the Blazor team on the [official repo](https://github.com/dotnet/aspnetcore). Or you could try asking in the [Blazor Gitter channel](https://gitter.im/aspnet/Blazor). This repo is for showcasing community Blazor contributions.

**Comment by AdrienTorris** [comment]
Or maybe StackOverflow? https://stackoverflow.com/search?q=blazor
I close the issue.

**Comment by Beblia** [comment]
Looks like there is no real fix for this. Maybe this is the blazor design for now? If anyone comes across this post please leave an answer if you have found a solution. Thanks.
