### ISSUE TITLE
How to Print particulate content <div> ... Content</div>   

### ISSUE THREAD

**Issue by AslalSujath** [AdrienTorris/awesome-blazor#290]
when I press a button. then print my content. 
please follow the link give your answer.

https://stackoverflow.com/questions/61471253/how-to-print-particulate-div-area-in-asp-net-core-component-razor

[](https://stackoverflow.com/questions/61471253/how-to-print-particulate-div-area-in-asp-net-core-component-razor)

**Comment by AdrienTorris** [comment]
This repository isn't the good place for this, consider asking your question here: https://docs.microsoft.com/en-us/answers/topics/364821/dotnet-aspnet-core-blazor.html
