### ISSUE TITLE
Consider adding the Nethereum Playground

### ISSUE THREAD

**Issue by juanfranblanco** [AdrienTorris/awesome-blazor#307]
You can see it running live here: http://playground.nethereum.com/

Provides an integrated Monaco IDE to edit and run Nethereum examples, or your own code (integrating mainly with Ethereum)
Provides an example of remote hosting .Net assemblies in IPFS, and register them in ENS, also it demonstrate the dynamic loading of modules / mini apps from a remote assembly hosted in IPFS.

Github repo https://github.com/Nethereum/Nethereum.Playground

**Comment by AdrienTorris** [comment]
Thanks!

**Comment by juanfranblanco** [comment]
Thanks to you !! :)
