### ISSUE TITLE
I never want to see the browser's scroll bars

### ISSUE THREAD

**Issue by scastria** [AdrienTorris/awesome-blazor#330]
One thing I hate about web UI compared to native UI is the interaction with the browser's dimensions and the UI's dimensions inside the browser.  Native UI controls usually include layout components to allow organizing child components on the screen.  I usually find that web UI lack the layout controls such that I usually see double scroll bars.  The scroll bar from the UI controls plus the scroll bars from the browser itself.

Is there a way to use Blazor WebAssembly so that I NEVER see the browser's scroll bars and that the top level parent of the blazor UI always resizes itself to match the browser and communicates that resize down to the blazor child UI components?

**Comment by AdrienTorris** [comment]
Hi,
This repository is not the good place for this, consider asking your question on StackOverflow or here https://docs.microsoft.com/en-us/answers/topics/364821/dotnet-aspnet-core-blazor.html
