### ISSUE TITLE
First 4 Demos now Missing

### ISSUE THREAD

**Issue by shawty** [AdrienTorris/awesome-blazor#34]
BlazorCalculator, BlazorChess, BlazorClockCanvas and BlazorClockSvg seem to have been remove from the URL's you point to.

EG: Chess one (Like the other 3 now do this)

![image](https://user-images.githubusercontent.com/1876454/47431364-8e28c100-d793-11e8-97b4-2af5d3bcfeee.png)

**Comment by shawty** [comment]
Working down through the demos, it would appear that all demos that where on

https://lupusablazordemos.azurewebsites.net/

are now unavailable as 

BlazorGameSnake, BlazorPasswordPattern and BlazorRawHtmlRenderer are also inaccessible.

**Comment by AdrienTorris** [comment]
Ok I'll check this. Thank's for your feedback.

**Comment by shawty** [comment]
No probs Adrien, just thought I'd let you know as I was trawling around looking for samples to understand how to build components.

I'm currently trying to hacktogether a blazor lib to wrap the summernote rich text editor and was looking for inspiration :-)

**Comment by AdrienTorris** [comment]
I updated the links, thank you very much for your feedback.
