### ISSUE TITLE
Question: Usage of IdentityServer4 within Hosted Blazor WebAssembly Project

### ISSUE THREAD

**Issue by mjfjansen** [AdrienTorris/awesome-blazor#407]
Does anyone have a working example wherein an IdentityServer4 service is called from a Hosted Blazor WebAssembly Project. For some reason this is the only projecttype which I cannot get to work with IdentityServer4.
Perhaps my current knowledge lacks on this part...
The case I am working on is:

The user selects to "login".
The user has to be ported to my identityserver, hosted on some server
The user is authenticated
Within the client project, I should be able to see the claims and be able to use the [Authorize] arguments
Within the controllers of de server project, I should be able to see the same and call other API's using the obtained access token.

**Comment by smallprogram** [comment]
I have tried to use Blazor Server to embed IdentityServer4. Use Blazor to implement the login and logout functions of the IdentityServer front-end. Then use a separate unmanaged Blazor WebAssembly as a client to access the Blazor Server hosted with IdentityServer4.

There were many problems during this period. Also solved many problems. Think about it later. It feels better to host IdentityServer4 in a traditional MVC project. Blazor WebAssembly still exists as a JavaScript client. Use OICD-Client.js to realize the interaction with IDP. Make another WebAPI for related background business.

**Comment by AdrienTorris** [comment]
Sorry but this repository is not the right place for this. Maybe some content of the last .NET Conf could interest you (https://www.youtube.com/watch?v=ecaiqrU_67k&list=PLdo4fOcmZ0oVFtp9MDEBNbA2sSqYvXSXO&index=41) otherwise consider asking your question on StackOverflow or the QA: https://docs.microsoft.com/en-us/answers/topics/364821/dotnet-aspnet-core-blazor.html
