### ISSUE TITLE
Question: how to print a pdf on a bluetooth printer in a webassembly application

### ISSUE THREAD

**Issue by gearsolutionschile** [AdrienTorris/awesome-blazor#411]
Hello, could someone guide me how to print a pdf on a printer
bluetooth with a webassembly application

**Comment by AdrienTorris** [comment]
Hi,
I'm sorry but this repository is not the good place for this kind of issue. Consider asking you question on StackOverflow or the QA : https://docs.microsoft.com/en-us/answers/topics/364821/dotnet-aspnet-core-blazor.html
