### ISSUE TITLE
Majority of the game related videos hosted on twitch are dead

### ISSUE THREAD

**Issue by adegeo** [AdrienTorris/awesome-blazor#504]
Twitch just says it's unavailable..

![image](https://user-images.githubusercontent.com/67293991/125814364-d74aa38d-4a18-4091-a67c-0cf511da8a68.png)

**Comment by AdrienTorris** [comment]
Thank's a lot.
I removed some dead links and will do another check soon.

**Comment by AdrienTorris** [comment]
I think there were sessions from CAnhorn: https://twitch.tv/canhorn
