### ISSUE TITLE
Add Blazor Analytics (Google Analytics integration)

### ISSUE THREAD

**Issue by isc30** [AdrienTorris/awesome-blazor#60]
Please add the Google Analytics component for tracking SPA activity

https://github.com/isc30/blazor-analytics
https://www.nuget.org/packages/Blazor-Analytics

Thanks

**Comment by AdrienTorris** [comment]
Hi.

It's done, thank you.

**Comment by AdrienTorris** [comment]
(I closed this issue, feel free to reopen it if you want)

**Comment by isc30** [comment]
thanks!
