### ISSUE TITLE
Consider Adding "Raw HTML Validation in Blazor" to articles.

### ISSUE THREAD

**Issue by shawty** [AdrienTorris/awesome-blazor#61]
I wrote this a few weeks ago, if you want to add it to the articles list

https://shawtyds.wordpress.com/2019/04/05/pure-html-validation-in-blazor/

Regards
Shawty

**Comment by shawty** [comment]
PS: Thanks for adding Blazor.SummerNote too

I need to add some more to it to be honest.

I also have a JWT Auth sample for blazor 0.7.0 on there, and I'm in the process of writing a usefull little intranet start/jump page portal with auth for the latest builds too.

**Comment by shawty** [comment]
PPS: Sorry, I've never done a pull req using GitHub before, so I've submitted like this.

**Comment by AdrienTorris** [comment]
Hi! 

I just add your article. Blazor.SummerNote is already mentioned in the samples.

**Comment by AdrienTorris** [comment]
I just add your other sample.

**Comment by AdrienTorris** [comment]
Don't worry about submitting this by an issue ;)

Have a good day

**Comment by AdrienTorris** [comment]
(I close this issue, feel free to reopen it if you need)

**Comment by shawty** [comment]
Hi Adrien, yea it's all good.  I have another sample to upload to my github too when I get it finished, I'll let you know when it's ready.

Thanks for the rest so far :-)

Hope to see you on gitter in the blazor room with us all sometime, would be great to get to know you
https://gitter.im/aspnet/Blazor
