### ISSUE TITLE
Difference between Extensions and Libraries

### ISSUE THREAD

**Issue by SamProf** [AdrienTorris/awesome-blazor#63]
I just want to understand  differences between this sub-headers.
1) Extensions - BlazorMaterial, Telerik UI for Blazor - something like components packs, but in Labraries we have MatBlazor and Blazorise - also components packs.
2) Extensions - BlazorConfirm, Toastr - so, some not big components, but in Libraries we have Blazored.Toast, BlazorScrollbar  and etc.

So, what difference. For me - this is one set of Libraries. What is reason to separate this?

**Comment by AdrienTorris** [comment]
Hello,

You're right. At the start it was two different way to consume external code but I agree that there is no more reason to separate them. It could be better to merge the 3 sections 'Extensions', 'Libraries' and 'Experiments & Sets of tools and libraries'. 

It's not that simple to keep it simple! :)

**Comment by AdrienTorris** [comment]
Which name for the new section? "Extensions & Libraries"?

**Comment by SamProf** [comment]
I think yes, we can merge this in one Libraries & Extensions.
Or we can separate 
* Components - more UI direction - Components pack,  like MatBlazor, Telerik UI for Blazor, Toastr , Menu and etc
* Libraries - more tooling direction like BlazorSignalR, Logging, Canvas, Blazor.Auth0 

But I think later sometimes we also will have problems to identify group of  Lib.
For we better is  ` Libraries & Extensions`.

Can I merge this groups and make PR?

**Comment by AdrienTorris** [comment]
I just merged your PR. Thank you.
