### ISSUE TITLE
Adding: BabylonBlazor,wrapping 3D library Babylon.js

### ISSUE THREAD

**Issue by sevencat** [AdrienTorris/awesome-blazor#640]
https://github.com/AlexNek/BabylonBlazor

[https://raw.githubusercontent.com/AlexNek/BabylonBlazor/master/docs/images/test1.png](url)

**Comment by sevencat** [comment]
[](url)[](url)
![test1](https://github.com/AdrienTorris/awesome-blazor/assets/4617072/ae5b8f53-c7c4-492f-93d6-c5edaf4ba30e)

**Comment by AdrienTorris** [comment]
Thanks!
