### ISSUE TITLE
Quick set of instructions on how to get blazor running on a Raspberry PI

### ISSUE THREAD

**Issue by shawty** [AdrienTorris/awesome-blazor#69]
Hi Adrian,

I've worked out today how to get the latest preview of Dotnet Core 3 + Blazor running on a raspberry PI V3, I've created a Gist here 

https://gist.github.com/shawty/a55f6d09edc2d381c8bd5bf2f639b2de

Explaining how.

**Comment by AdrienTorris** [comment]
Hi,

It's very interesting. 

I don't know in which section add this link (tutorial? sample?). It would be perfect if it has been a blog post :)

Give me one more day to think about where to add this link but I definitely will.

**Comment by shawty** [comment]
Yea, it is a tough decision.  I'm away at a fair all weekend, won't be back until Monday, if I have time I might be able to do it as a blog post.

**Comment by shawty** [comment]
Not going to have time to blog post this, for a week or two, so maybe misc or tutorial for now, then we can move later.

**Comment by AdrienTorris** [comment]
Added to the tutorials. Thank's for the submission and your patience!

**Comment by shawty** [comment]
Anytime Adrien.

You should pop your head into the gitter chat room at: https://gitter.im/aspnet/Blazor there's always tons of URL's and discussions going on about things that the community have done, or are doing with Blazor.

I'll let you know when my "Intranet Jump/Start page/app" is done.

Shawty
