### ISSUE TITLE
Please consider adding BlazorUnmarshalledCanvas

### ISSUE THREAD

**Issue by jhwcn** [AdrienTorris/awesome-blazor#70]
https://github.com/jhwcn/BlazorUnmarshalledCanvas

Another HTML5 Canvas 2d context API implementation, but it uses the unmarshalled Invoke methods to boost the performance, and it can be extended easily.

Thanks.

**Comment by AdrienTorris** [comment]
Hi!

It's done. Thank you for this sample.

**Comment by AdrienTorris** [comment]
(Feel free to reopen this issue if you need)
