### ISSUE TITLE
Client- and server-side RealWorld examples

### ISSUE THREAD

**Issue by burke166** [AdrienTorris/awesome-blazor#73]
Here are some updated [RealWorld](https://github.com/gothinkster/realworld) repos and demos for both client-side and server-side Blazor.

[Server-side Repo](https://github.com/burke166/blazor-server-side-realworld-example-app)
[Server-side Demo](https://blazorserverside.computercodeblue.com/)

[Client-side Repo](https://github.com/burke166/blazor-client-side-realworld-example-app)
[Client-side Demo](https://blazorclientside.computercodeblue.com/)

**Comment by AdrienTorris** [comment]
I'll check this today! Thank's for the submission.

**Comment by AdrienTorris** [comment]
Thank's for the submission.
