### ISSUE TITLE
Consider Adding Radzen

### ISSUE THREAD

**Issue by b3nda1ley** [AdrienTorris/awesome-blazor#93]
Radzen RAD Tool: https://www.radzen.com

Radzen Components: https://github.com/akorchev/razor.radzen.com

Thanks for maintaining this list.

**Comment by AdrienTorris** [comment]
![radzen](https://user-images.githubusercontent.com/1014357/59256303-f5688800-8c33-11e9-9bd7-1e58d5338010.PNG)

No it's not :)

**Comment by AdrienTorris** [comment]
I am a little stuck with this submission (but thank you very much).

What is Radzen exactly? A Framework?

**Comment by imtrobin** [comment]
I was trying it recently, it's a RAD tool. I couldn't get their a simple example to run, I didn't bother to try to solve it and went back to coding it myself.

**Comment by b3nda1ley** [comment]
Yep it'

> I am a little stuck with this submission (but thank you very much).
> 
> What is Radzen exactly? A Framework?

It's a RAD tool originally generating .NET Core back ends with Angular front ends but it appears they are retooling the front end generation for Blazor. They indicate the Blazor components will be free independent of the tool cf https://www.radzen.com/blog/build-web-applications-with-radzen-blazor-csharp-no-javascript-required/

**Comment by b3nda1ley** [comment]
I see it's been added now so I'm closing this thanks.
