### ISSUE TITLE
Brazilian Blog dedicated to Blazor

### ISSUE THREAD

**Issue by rodrigosendin** [AdrienTorris/awesome-blazor#98]
Do you include material in other languages? If so, this blog: blazeofcode.com has more than 40 articles of Blazor, and it is been updated every week,

**Comment by stsrki** [comment]
@rodrigosendin I must say you have made an excellent blog. Have you considered to translate it to English? I'm sure it would attract much more users.

**Comment by AdrienTorris** [comment]
Hi Rodrigo.

Thank you for this issue, it's an interesting point. I already think about adding some resources in other languages (see the issue #20 ) but I don't know how to do this to keep this repo simple and clear.

We can:
   - Add some localized readme files (like readme-fr.md, readme-pt.md, ...) but I'm afraid to have multiple files with just a few lines.
   - Add a section "Other languages" in the readme file).
   - Other idea?

For now I vote to add a section "Other languages" in the readme file. 
**What's your opinion?**

**Comment by AdrienTorris** [comment]
Congrat's @rodrigosendin for your blog by the way, I don't speak Portuguese but it seems very great 👍 
We definitely have to mention it. We just have to decide how.

**Comment by rodrigosendin** [comment]
> * Other languages

Hello Adrien! 

Thanks for the feedback! I think that a section "Other Languages" is a perfect solution.

**Comment by rodrigosendin** [comment]
> @rodrigosendin I must say you have made an excellent blog. Have you considered to translate it to English? I'm sure it would attract much more users.

Thanks for the feedback, and the suggestion! I will think about it. 
I´ve choosed portugues because I am trying to bring some brazilian devs to the Blazor side of the web ;)
But I will try to plan a translated version of the articles.

**Comment by AdrienTorris** [comment]
Section added. Is it ok for you?

**Comment by rodrigosendin** [comment]
It is AWESOME!! 
It's an honor to be part of this list
Thanks!

**Comment by AdrienTorris** [comment]
It's an honor for us to mention your great blog ;)
Keep going 👍
