### ISSUE TITLE
Consider adding a deprecated section in README.md

### ISSUE THREAD

**Issue by stavroskasidis** [AdrienTorris/awesome-blazor#99]
Some samples/libraries are either a very old preview or deprecated making them unusable and filling the README.md with noise.

Would you consider adding a **Deprecated** section (at the bottom?), so that stuff that are considered deprecated can be moved in there? 

I suppose there could be some kind of process that the author of the link is notified for the deprecation and is given the opportunity to either update or remove the link.

**Comment by AdrienTorris** [comment]
Hello,

Your point is interesting. I agree, adding a 'Deprecated' section for the libraries and samples makes sense.

**Comment by AdrienTorris** [comment]
Section added. I think we will need a "procedure" to deprecate a resource, like creating an issue first like "Considering deprecate the library X".

**Comment by AdrienTorris** [comment]
#105 #106 #107 #108 #109 #110 #111 #112 #113 #114 #115 #116 #117 #118 #119 #120 #121 #122 #123 #124

**Comment by AdrienTorris** [comment]
The cleaning is in progress. I close this issue, feel free to reopen it if you want.
